name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: make
      run: make all -j4 BUILD_TARGET=release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: ./msghide
        if-no-files-found: error
